services:
  dds:
    image: http-dds-bridge
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    tty: true
    stdin_open: true
    ports:
      - "5000:5000"  